# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legislators', '0012_auto_20170724_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=100)),
                ('document_date', models.DateField()),
                ('document_title', models.CharField(max_length=255)),
                ('fragment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterestingSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='interestingsearch',
            name='entities',
            field=models.ManyToManyField(to='interesting.NamedEntity'),
        ),
        migrations.AddField(
            model_name='interestingsearch',
            name='search_terms',
            field=models.ManyToManyField(to='interesting.SearchTerm'),
        ),
        migrations.AddField(
            model_name='foundresult',
            name='interesting_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interesting.InterestingSearch'),
        ),
        migrations.AddField(
            model_name='foundresult',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislators.CongressPerson'),
        ),
    ]
