# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0012_auto_20170724_1925'),
        ('interesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestingsearch',
            options={'verbose_name_plural': 'interestingsearches'},
        ),
        migrations.AlterModelOptions(
            name='namedentity',
            options={'verbose_name_plural': 'namedentities'},
        ),
        migrations.AlterUniqueTogether(
            name='foundresult',
            unique_together=set([('interesting_search', 'speaker', 'document_id')]),
        ),
    ]
