# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:08
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interesting', '0002_auto_20170727_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundresult',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foundresult',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
