# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interesting', '0003_auto_20170728_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundresult',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interestingsearch',
            name='entities',
            field=models.ManyToManyField(blank=True, to='interesting.NamedEntity'),
        ),
        migrations.AlterField(
            model_name='interestingsearch',
            name='search_terms',
            field=models.ManyToManyField(blank=True, to='interesting.SearchTerm'),
        ),
    ]
