# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interesting', '0004_auto_20170728_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundresult',
            name='fragment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
