# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interesting', '0005_auto_20170728_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundresult',
            name='fragment',
            field=models.TextField(default=''),
        ),
    ]
